---
namespace: oreol
name: mgmt
version: 0.1.0
readme: README.md
authors:
  - Oreol
description: Reusable Ansible automation for cluster configuration and management.
license:
  - MIT
repository: https://github.com/oreolag/ansible-collection
dependencies:
  ansible.posix: ">=1.0.0"
build_ignore:
  - .DS_Store
  - "**/.DS_Store"
