---
- name: Configure login users with matching public keys
  ansible.builtin.include_tasks: user.yml
  loop: "{{ users.login | default([]) }}"
  loop_control:
    loop_var: login_useradd_username
  vars:
    login_useradd_public_key: >-
      {{ lookup('ansible.builtin.file', inventory_dir ~ '/keys/' ~ login_useradd_username ~ '.pub',
                errors='ignore') | default('', true) }}
